version: 0.2

phases:
  pre_build:
    commands:
      - echo "Changing into source directory $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      - echo Zip lambda function and lambda layer...
      - dateTime=$(date +"%Y-%m-%d-%H-%M-%S")
      - LambdaZipVersion="$Lambda"-"$dateTime".zip
      - LambdaLayerZipVersion="$LambdaLayer"-"$dateTime".zip
      - zip -r "$LambdaZipVersion" lambda
      - zip -r "$LambdaLayerZipVersion" aws_embedded_metrics
  build:
    commands:
      - ls
      - echo Uploading Lambda and  Layer zip file to S3 Bucket
      - aws s3 sync . s3://"$S3_BUCKET"/  --exclude "*" --include "*.zip"
      - echo Successfully uploaded Lambda and Lambda Layer to "$S3_BUCKET"
  post_build:
    commands:
      - echo Deploying the CF
      - chmod +x create-update-stack.sh
      - ./create-update-stack.sh myGluejobsCustomMetrics $LambdaZipVersion $LambdaLayerZipVersion
      - echo CF Deployment successful
artifacts:
  files:
    - "**/*"